OS:osx
language: swift
osx_image: xcode13.2
script: 'xcodebuild clean test -project CI_experiment.xcodeproj -scheme "CI_experiment" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=15.2,name=iPhone 13 Pro" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO'
notifications:
    email:
        recipients:
            - hungnt1486@gmail.com
            - hung@modmo.io
        on_success: always
        on_failure: always
